version: '3'

services:
  lfc_nginx:
    image: nginx
    container_name: lfc_nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - 80:80
      - 3000:443
    restart: always
    links:
      - lfc_php
  lfc_php:
    image: nanoninja/php-fpm:latest
    container_name: lfc_php
    expose:
      - 9000
    restart: always
    volumes:
      - ./:/var/www
    links:
      - lfc_mysql
  lfc_mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: lfc_mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=lfc_mysql
      - PMA_USER=${MYSQL_ROOT_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    links:
      - lfc_mysql
